=== wumykj/competition/20数学建模省赛/code/lcdata.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<!-- MathWorks Locale Database Schema -->
<!-- File Name: lcdata.xsd -->
<!-- Copyright 2007-2014 The MathWorks, Inc. -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="lcdata">
        <xsd:complexType>
	    <xsd:sequence>
	        <xsd:element name="locale" type="locale_type" minOccurs="0" maxOccurs="unbounded" />
	        <xsd:element name="codeset" type="codeset_type" minOccurs="1" maxOccurs="1" />
	    </xsd:sequence>
	</xsd:complexType>
    </xsd:element> 

    <xsd:complexType name="locale_type">
        <xsd:sequence>
            <xsd:element name="l10n" type="l10n_type" minOccurs="0" maxOccurs="1" />
            <xsd:element name="javafont" type="font_type" minOccurs="0" maxOccurs="3" />
            <xsd:element name="alias" type="alias_type" minOccurs="1" maxOccurs="unbounded" />
        </xsd:sequence>
    	<xsd:attribute name="name" type="xsd:string" use="required" />
    	<xsd:attribute name="encoding" type="xsd:string" use="required" />
    	<xsd:attribute name="xpg_name" type="xsd:string" use="optional" />
    </xsd:complexType> 

    <xsd:complexType name="l10n_type">
    	<xsd:attribute name="disable" use="required">
    	    <xsd:simpleType>
    	        <xsd:restriction  base="xsd:string">
    		    <xsd:pattern value="[LOW]{1,3}" />
    		</xsd:restriction>
    	    </xsd:simpleType>
    	</xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="font_type">
    	<xsd:attribute name="os" use="required">
    	    <xsd:simpleType>
    	        <xsd:restriction  base="xsd:string">
    		    <xsd:pattern value="[LOW]{1,3}" />
    		</xsd:restriction>
    	    </xsd:simpleType>
    	</xsd:attribute>
    	<xsd:attribute name="dialog" type="xsd:string" use="optional" />
    	<xsd:attribute name="dialog_input" type="xsd:string" use="optional" />
    	<xsd:attribute name="monospaced" type="xsd:string" use="optional" />
    	<xsd:attribute name="sans_serif" type="xsd:string" use="optional" />
    	<xsd:attribute name="serif" type="xsd:string" use="optional" />
    </xsd:complexType>
	
    <xsd:complexType name="alias_type">
    	<xsd:attribute name="name" type="xsd:string" use="required" />
    </xsd:complexType>

    <xsd:complexType name="codeset_type">
        <xsd:sequence>
            <xsd:element name="encoding" type="encoding_type" minOccurs="0" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType> 

    <xsd:complexType name="encoding_type">
        <xsd:sequence>
            <xsd:element name="encoding_alias" type="encoding_alias_type" minOccurs="0" maxOccurs="unbounded" />
        </xsd:sequence>
    	<xsd:attribute name="name" type="xsd:string" use="required" />
    	<xsd:attribute name="jvm_encoding" type="xsd:string" use="optional" />
    </xsd:complexType> 

    <xsd:complexType name="encoding_alias_type">
    	<xsd:attribute name="name" type="xsd:string" use="required" />
    </xsd:complexType> 
</xsd:schema>

=== wumykj/competition/20数学建模省赛/code/lcdata_utf8.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- MathWorks Locale Database -->
<!-- File Name: lcdata_utf8.xml -->
<!-- Copyright 2007-2015 The MathWorks, Inc. -->
<lcdata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="lcdata.xsd">
    <!-- Locale entries -->
    <locale name="aa_DJ" encoding="ISO-8859-1"/>
    <locale name="aa_ER" encoding="UTF-8"/>
    <locale name="aa_ET" encoding="UTF-8"/>
    <locale name="af_ZA" encoding="UTF-8" xpg_name="af_ZA.UTF-8">
        <alias name="af"/>
    </locale>
    <locale name="am_ET" encoding="UTF-8" xpg_name="am_ET.UTF-8">
        <alias name="am"/>
    </locale>
    <locale name="an_ES" encoding="ISO-8859-15"/>
    <locale name="ar_EG" encoding="ISO-8859-6">
        <alias name="Ar"/>
    </locale>
    <locale name="ar_AE" encoding="ISO-8859-6"/>
    <locale name="ar_BH" encoding="ISO-8859-6"/>
    <locale name="ar_DZ" encoding="ISO-8859-6"/>
    <locale name="ar_IN" encoding="UTF-8"/>
    <locale name="ar_IQ" encoding="ISO-8859-6"/>
    <locale name="ar_JO" encoding="ISO-8859-6"/>
    <locale name="ar_KW" encoding="ISO-8859-6"/>
    <locale name="ar_LB" encoding="ISO-8859-6"/>
    <locale name="ar_LY" encoding="ISO-8859-6"/>
    <locale name="ar_MA" encoding="ISO-8859-6"/>
    <locale name="ar_OM" encoding="ISO-8859-6"/>
    <locale name="ar_QA" encoding="ISO-8859-6"/>
    <locale name="ar_SA" encoding="ISO-8859-6"/>
    <locale name="ar_SD" encoding="ISO-8859-6"/>
    <locale name="ar_SY" encoding="ISO-8859-6"/>
    <locale name="ar_TN" encoding="ISO-8859-6"/>
    <locale name="ar_YE" encoding="ISO-8859-6"/>
    <locale name="arn_CL" encoding="windows-1252"/>
    <locale name="as_IN" encoding="UTF-8"/>
    <locale name="ast_ES" encoding="ISO-8859-15"/>
    <locale name="az-Cyrl_AZ" encoding="windows-1251"/>
    <locale name="az-Latn_AZ" encoding="windows-1254"/>
    <locale name="az_AZ" encoding="UTF-8"/>
    <locale name="be_BY" encoding="UTF-8" xpg_name="be_BY.UTF-8">
        <alias name="be"/>
    </locale>
    <locale name="ber_DZ" encoding="UTF-8"/>
    <locale name="ber_MA" encoding="UTF-8"/>
    <locale name="bg_BG" encoding="UTF-8" xpg_name="bg_BG.UTF-8">
        <alias name="bg"/>
    </locale>
    <locale name="bn_BD" encoding="UTF-8"/>
    <locale name="bn_IN" encoding="UTF-8"/>
    <locale name="br_FR" encoding="ISO-8859-1">
        <alias name="br"/>
    </locale>
    <locale name="bs-Cyrl_BA" encoding="windows-1251"/>
    <locale name="bs-Latn_BA" encoding="windows-1250"/>
    <locale name="bs_BA" encoding="ISO-8859-2"/>
    <locale name="byn_ER" encoding="UTF-8"/>
    <locale name="en_US_POSIX" encoding="US-ASCII" xpg_name="C">
        <alias name="C"/>
        <alias name="POSIX"/>
    </locale>
    <locale name="ca_AD" encoding="ISO-8859-15"/>
    <locale name="ca_ES" encoding="UTF-8" xpg_name="ca_ES.UTF-8">
        <alias name="ca"/>
    </locale>
    <locale name="ca_FR" encoding="ISO-8859-15"/>
    <locale name="ca_IT" encoding="ISO-8859-15"/>
    <locale name="crh_UA" encoding="UTF-8"/>
    <locale name="cs_CZ" encoding="UTF-8" xpg_name="cs_CZ.UTF-8">
        <alias name="cs"/>
        <alias name="cs_CS"/>
        <alias name="cz"/>
        <alias name="cz_CZ"/>
    </locale>
    <locale name="csb_PL" encoding="UTF-8"/>
    <locale name="cy_GB" encoding="ISO-8859-1">
        <alias name="cy"/>
    </locale>
    <locale name="da_DK" encoding="UTF-8" xpg_name="da_DK.UTF-8">
        <alias name="da"/>
    </locale>
    <locale name="de_DE" encoding="UTF-8" xpg_name="de_DE.UTF-8">
        <alias name="de"/>
    </locale>
    <locale name="de_AT" encoding="UTF-8" xpg_name="de_AT.UTF-8">
        <alias name="de-AT"/>
    </locale>
    <locale name="de_CH" encoding="UTF-8" xpg_name="de_CH.UTF-8">
        <alias name="de-CH"/>
    </locale>
    <locale name="de_BE" encoding="ISO-8859-15"/>
    <locale name="de_LI" encoding="windows-1252"/>
    <locale name="de_LU" encoding="ISO-8859-15"/>
    <locale name="dsb_DE" encoding="windows-1252"/>
    <locale name="dz_BT" encoding="UTF-8"/>
    <locale name="ee_EE" encoding="ISO-8859-4">
        <alias name="ee"/>
    </locale>
    <locale name="el_CY" encoding="ISO-8859-7"/>
    <locale name="el_GR" encoding="UTF-8" xpg_name="el_GR.UTF-8">
        <alias name="el"/>
    </locale>
    <locale name="en_US" encoding="UTF-8" xpg_name="en_US.UTF-8">
        <alias name="en"/>
        <alias name="en-US"/>
    </locale>
    <locale name="en_AU" encoding="UTF-8" xpg_name="en_AU.UTF-8">
        <alias name="en-AU"/>
    </locale>
    <locale name="en_CA" encoding="UTF-8" xpg_name="en_CA.UTF-8">
        <alias name="en-CA"/>
    </locale>
    <locale name="en_GB" encoding="UTF-8" xpg_name="en_GB.UTF-8">
        <alias name="en-GB"/>
        <alias name="en_UK"/>
    </locale>
    <locale name="en_029" encoding="windows-1252">
        <alias name="en_CB"/>
    </locale>
    <locale name="en_BE" encoding="ISO-8859-1"/>
    <locale name="en_BW" encoding="ISO-8859-1"/>
    <locale name="en_BZ" encoding="windows-1252"/>
    <locale name="en_DK" encoding="ISO-8859-1"/>
    <locale name="en_HK" encoding="ISO-8859-1"/>
    <locale name="en_IE" encoding="UTF-8" xpg_name="en_IE.UTF-8"/>
    <locale name="en_IN" encoding="UTF-8"/>
    <locale name="en_JM" encoding="windows-1252"/>
    <locale name="en_MY" encoding="windows-1252"/>
    <locale name="en_NG" encoding="UTF-8"/>
    <locale name="en_NZ" encoding="UTF-8" xpg_name="en_NZ.UTF-8"/>
    <locale name="en_PH" encoding="ISO-8859-1"/>
    <locale name="en_SG" encoding="ISO-8859-1"/>
    <locale name="en_TT" encoding="windows-1252"/>
    <locale name="en_ZA" encoding="ISO-8859-1"/>
    <locale name="en_ZW" encoding="ISO-8859-1"/>
    <locale name="es_ES" encoding="UTF-8" xpg_name="es_ES.UTF-8">
        <alias name="es"/>
        <alias name="es-ES"/>
    </locale>
    <locale name="es_AR" encoding="ISO-8859-1"/>
    <locale name="es_BO" encoding="ISO-8859-1"/>
    <locale name="es_CL" encoding="ISO-8859-1"/>
    <locale name="es_CO" encoding="ISO-8859-1"/>
    <locale name="es_CR" encoding="ISO-8859-1"/>
    <locale name="es_DO" encoding="ISO-8859-1"/>
    <locale name="es_EC" encoding="ISO-8859-1"/>
    <locale name="es_GT" encoding="ISO-8859-1"/>
    <locale name="es_HN" encoding="ISO-8859-1"/>
    <locale name="es_MX" encoding="ISO-8859-1"/>
    <locale name="es_NI" encoding="ISO-8859-1"/>
    <locale name="es_PA" encoding="ISO-8859-1"/>
    <locale name="es_PE" encoding="ISO-8859-1"/>
    <locale name="es_PR" encoding="ISO-8859-1"/>
    <locale name="es_PY" encoding="ISO-8859-1"/>
    <locale name="es_SV" encoding="ISO-8859-1"/>
    <locale name="es_US" encoding="ISO-8859-1"/>
    <locale name="es_UY" encoding="ISO-8859-1"/>
    <locale name="es_VE" encoding="ISO-8859-1"/>
    <locale name="et_EE" encoding="UTF-8" xpg_name="et_EE.UTF-8">
        <alias name="et"/>
    </locale>
    <locale name="eu_ES" encoding="UTF-8" xpg_name="eu_ES.UTF-8">
        <alias name="eu"/>
    </locale>
    <locale name="eu_FR" encoding="ISO-8859-1"/>
    <locale name="fa_IR" encoding="UTF-8">
        <alias name="fa"/>
    </locale>
    <locale name="fi_FI" encoding="UTF-8" xpg_name="fi_FI.UTF-8">
        <alias name="fi"/>
    </locale>
    <locale name="fil_PH" encoding="windows-1252"/>
    <locale name="fo_FO" encoding="ISO-8859-1">
        <alias name="fo"/>
    </locale>
    <locale name="fr_FR" encoding="UTF-8" xpg_name="fr_FR.UTF-8">
        <alias name="fr"/>
    </locale>
    <locale name="fr_CA" encoding="UTF-8" xpg_name="fr_CA.UTF-8">
        <alias name="fr-CA"/>
    </locale>
    <locale name="fr_CH" encoding="UTF-8" xpg_name="fr_CH.UTF-8">
        <alias name="fr-CH"/>
    </locale>
    <locale name="fr_BE" encoding="UTF-8" xpg_name="fr_BE.UTF-8"/>
    <locale name="fr_LU" encoding="ISO-8859-15"/>
    <locale name="fr_MC" encoding="windows-1252"/>
    <locale name="fur_IT" encoding="UTF-8"/>
    <locale name="fy_DE" encoding="UTF-8"/>
    <locale name="fy_NL" encoding="windows-1252"/>
    <locale name="ga_IE" encoding="ISO-8859-1">
        <alias name="ga"/>
    </locale>
    <locale name="gbz_AF" encoding="windows-1256"/>
    <locale name="gd_GB" encoding="ISO-8859-1">
        <alias name="gd"/>
    </locale>
    <locale name="gez_ER" encoding="UTF-8"/>
    <locale name="gez_ET" encoding="UTF-8"/>
    <locale name="gl_ES" encoding="ISO-8859-1">
        <alias name="gl"/>
    </locale>
    <locale name="gu_IN" encoding="UTF-8">
        <alias name="gu"/>
    </locale>
    <locale name="gv_GB" encoding="ISO-8859-1">
        <alias name="gv"/>
    </locale>
    <locale name="ha-Latn_NG" encoding="windows-1252">
        <alias name="ha_NG"/>
    </locale>
    <locale name="he_IL" encoding="UTF-8" xpg_name="he_IL.UTF-8">
        <alias name="He"/>
        <alias name="iw"/>
        <alias name="iw_IL.iso88598"/>
    </locale>
    <locale name="hi_IN" encoding="UTF-8">
        <alias name="hi"/>
    </locale>
    <locale name="hr_HR" encoding="UTF-8" xpg_name="hr_HR.UTF-8">
        <alias name="hr"/>
        <alias name="sh_HR"/>
    </locale>
    <locale name="hr_BA" encoding="windows-1250"/>
    <locale name="hsb_DE" encoding="windows-1252"/>
    <locale name="hu_HU" encoding="UTF-8" xpg_name="hu_HU.UTF-8">
        <alias name="hu"/>
    </locale>
    <locale name="hy_AM" encoding="UTF-8" xpg_name="hy_AM.UTF-8">
        <alias name="hy"/>
        <alias name="hy_AM_REVISED"/>
    </locale>
    <locale name="id_ID" encoding="ISO-8859-1">
        <alias name="id"/>
        <alias name="in"/>
        <alias name="in_ID"/>
    </locale>
    <locale name="ig_NG" encoding="UTF-8"/>
    <locale name="ik_CA" encoding="UTF-8"/>
    <locale name="is_IS" encoding="UTF-8" xpg_name="is_IS.UTF-8">
        <alias name="is"/>
    </locale>
    <locale name="it_IT" encoding="UTF-8" xpg_name="it_IT.UTF-8">
        <alias name="it"/>
    </locale>
    <locale name="it_CH" encoding="UTF-8" xpg_name="it_CH.UTF-8"/>
